project_id = "vdjcdvhjcagqwkhgaivs"

[functions.google-calendar-auth]
verify_jwt = false

[functions.google-calendar-event]
verify_jwt = false

[functions.google-calendar-events]
verify_jwt = false

[functions.google-calendar-manage]
verify_jwt = false